# fly.toml app configuration file generated for daniel-blog-18-i7g on 2025-07-03T06:37:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daniel-blog-18-i7g'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
